name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x]
        # browser: [firefox, chrome]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install yarn
        run: npm i -g yarn
      - name: Install project dependencies
        run: npx yarn install
      - name: Run tests
        run: npm test
